### ISSUE TITLE
docker-compose up后无法报错 队列空了，坏！

### ISSUE THREAD

**Issue by vlinux** [xiongnemo/sese-engine-docker#1]
![image](https://user-images.githubusercontent.com/73208462/180413257-89b874e4-2d8a-404c-b9ed-c0d8649bb2a7.png)

**Comment by xiongnemo** [comment]
你是自己从头编译了镜像还是直接用 Docker Hub 上面的？

**Comment by vlinux** [comment]
我直接用的你Dockerhub上面的，未做任何修改，直接docker-compose up。然后我请求那个端口并且携带了参数，有服务响应，但无数据响应
还有我想请问一下，docker-compose.yaml中的HTTPS_PROXY这个配置，代表着什么？有什么具体含义咩？






在 2022年7月26日 14:12，Nemo ***@***.***> 写道：


你是自己从头编译了镜像还是直接用 Docker Hub 上面的？

**Comment by xiongnemo** [comment]
> 我直接用的你Dockerhub上面的，未做任何修改，直接docker-compose up。然后我请求那个端口并且携带了参数，有服务响应，但无数据响应 还有我想请问一下，docker-compose.yaml中的HTTPS_PROXY这个配置，代表着什么？有什么具体含义咩？ 在 2022年7月26日 14:12，Nemo ***@***.***> 写道： 你是自己从头编译了镜像还是直接用 Docker Hub 上面的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

`HTTPS_PROXY` 如果自己的互联网连接不需要的话可以直接删掉的，可以参考 https://stackoverflow.com/questions/58559109/difference-between-http-proxy-and-https-proxy

即使全部配置正确的话，从开始爬取到能返回有效的搜索结果（大清洗完成）也需要一定时间。

与这个 repo 本身没有关系的问题建议在 [本体](https://github.com/RimoChan/sese-engine) 处提 issue。
