### ISSUE TITLE
是否可以增加aarch64的支持

### ISSUE THREAD

**Issue by mengguyi** [xiongnemo/sese-engine-docker#2]
刀客集线器上的镜像全是amd64的，是否可以编译一个aarch64的呢

**Comment by xiongnemo** [comment]
好的，等我明年初摇滚派五比到了就试试（咕咕咕

**Comment by xiongnemo** [comment]
> 刀客集线器上的镜像全是amd64的，是否可以编译一个aarch64的呢

试试 `anzupop/sese-engine:alpine-aarch64` ?

![image](https://user-images.githubusercontent.com/38759782/210125699-12912364-41a1-4a35-875c-6a7369456be9.png)

**Comment by mengguyi** [comment]
我自己拿你的代码构建了一个
